#!/bin/bash
if ls *.err 1> /dev/null 2>&1; then rm *.err; fi
if ls *.arg 1> /dev/null 2>&1; then rm *.arg; fi
if ls *.std 1> /dev/null 2>&1; then rm *.std; fi
if ls *.rslt 1> /dev/null 2>&1; then rm *.rslt; fi
if ls *.pdf 1> /dev/null 2>&1; then rm *.pdf; fi
if ls checkpoints/*rslt 1> /dev/null 2>&1; then rm checkpoints/*rslt; fi
if ls checkpoints/*gz 1> /dev/null 2>&1; then rm checkpoints/*gz; fi
if ls hostGraphs/* 1> /dev/null 2>&1; then rm hostGraphs/*; fi
if ls *Frame.* 1> /dev/null 2>&1; then rm *Frame.*; fi
